// <auto-generated />
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260219180032_UpdateBookStatusString")]
    partial class UpdateBookStatusString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "book_status", new[] { "available", "borrowed", "reserved" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryApp.models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1828,
                            Country = "Russia",
                            Name = "Lev Tolstoi"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1821,
                            Country = "Russia",
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1965,
                            Country = "United Kingdom",
                            Name = "Joanne Rowling"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1903,
                            Country = "United Kingdom",
                            Name = "Jorj Oruell"
                        });
                });

            modelBuilder.Entity("LibraryApp.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Pages = 1225,
                            Status = "Available",
                            Title = "Peace and war",
                            Year = 1869
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Pages = 864,
                            Status = "Available",
                            Title = "Anna Karenina",
                            Year = 1877
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Pages = 671,
                            Status = "Available",
                            Title = "Crime and Punishment",
                            Year = 1866
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Pages = 796,
                            Status = "Available",
                            Title = "The Brothers Karamazov",
                            Year = 1880
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Pages = 223,
                            Status = "Available",
                            Title = "Harry Potter and the Philosopher's Stone",
                            Year = 1977
                        });
                });

            modelBuilder.Entity("LibraryApp.models.Book", b =>
                {
                    b.HasOne("LibraryApp.models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryApp.models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
